### ISSUE TITLE
Change signature with nested functions

### ISSUE THREAD

**Issue by marabesi** [nicoespeon/abracadabra#1085]
## Describe the bug

Given two nested functions, using change signature will always take the outer most function instead of the one at the cursor.

## How to reproduce

In the following video, there two functions `statement` and `amountFor`. amountFor is inside `statement`. When applying change signature, the extension targets `statement` function. The change signature even list the `statement` parameters in the change signature panel on on the right, however, when applying the refactor it applies in the `amountFor` function.

https://github.com/user-attachments/assets/6c5e1b9b-75fa-404c-9b7b-a9ef5e082726

Source code being used: https://github.com/marabesi/katas-playground/blob/9d9f23d96af93a3bc0d2aaeea4a0c59265d8e293/solutions/theatrical-players-refactoring/src/statement.ts

## Expected behavior

Change signature should take into account the function at the cursor instead of the outer most function

## Additional information

- Version of the extension impacted: v9.4.7

Here goes the dialog that webstorm opens (and is the expected one):

<img width="922" alt="image" src="https://github.com/user-attachments/assets/916d1247-90b6-455b-8276-7cd435728f6c">

**Comment by nicoespeon** [comment]
Thank you for the very detailed report @marabesi, that was really helpful to repro and understand what was missing. Turns out this refactoring was not properly checking if a nested function would match the requested refactoring closer, and so it was picking the top-level one.

This should be fixed. I've tried with a similar code and it's working fine now. I'm shipping a new release so you should be able to use it too 😉

**Comment by nicoespeon** [comment]
@all-contributors please add marabesi for bugs

**Comment by marabesi** [comment]
wow, that was fast. Thanks for that!
