### ISSUE TITLE
New refactoring: Convert function reference to arrow function

### ISSUE THREAD

**Issue by automatensalat** [nicoespeon/abracadabra#110]
## Is this request related to a problem? Please describe.

I often have the use case that I want to add another statement to a function where we currently pass a function reference. Consider this jest code: 
```ts
beforeEach(jest.clearAllMocks);
```
If I want to add something to the test setup I have to convert this expression manually to an arrow function like so: 
```ts
beforeEach(() => {
  jest.clearAllMocks();
});
```
then add the additional code in the body of the arrow function.

## Describe the solution you'd like

I'd like to have a new refactoring that does this conversion for me. 
It would find out that the selected identifier describes a function (in this example `jest.clearAllMocks`) and ideally its signature (in case of Typescript). Depending on the signature of the function reference the refactoring would replace the function reference `fn` with either `() => {  fn(); }` (if fn returns void) or `() => {  return fn(); }` (any other case). 
If the target function expects a parameter we could generate `(arg) => {  fn(arg); }` or `(arg) => {  return fn(arg); }` respectively.

**Comment by nicoespeon** [comment]
That's an interesting refactoring indeed.

Of course, the tricky part will be to retrieve the signature of the function 🤔 
We'll need to think about it.

**Comment by OliverJAsh** [comment]
Just wanted to say that it would also be useful to provide a refactoring that converts in the opposite direction.

**Comment by nicoespeon** [comment]
@OliverJAsh yep, you're right.

There's something I missed with this suggestion that makes me think we can't easily do this. Regardless of the arguments, there's the notion of binding that is different.

```js
beforeEach(jest.clearAllMocks);
```

And 

```js
beforeEach(() => {
  jest.clearAllMocks();
});
```

May not behave the same at runtime, it depends if `jest.clearAllMocks()` refers to `this` or not. 

That makes this refactoring much more complex to perform safely. Hence, I'm not sure that would be a reasonable one to do. Open to discussions though 👐

**Comment by OliverJAsh** [comment]
That's a very good point. Nonetheless, it would still be very useful to offer this refactoring, without any guarantees that it won't break the code, so that we can automate this conversion when we know it is safe to do so. Perhaps we could add a warning somewhere?

**Comment by OliverJAsh** [comment]
Quick note to mention another example where this could break code:

```ts
xs.map(x => parseInt(x)) // ✅ no radix param

xs.map(parseInt) // ❌ index is being passed as radix
```

**Comment by nicoespeon** [comment]
Yep, this would be useful, but it's tricky.

Ideally, the refactoring would detect the problematic cases and won't execute the refactoring in these cases:
- function calls `this` and is not bound to the scope of the arrow function that would be generated
- function would receive different arguments that it expects (the case of `parseInt`)

In these cases, we wouldn't propose the Quick Fix and show an explicit error message if the user tries to execute the refactoring. We may even show a warning to explain why the Quick Fix is not proposed.

Now, that would be The Ideal Case™.

As a first iteration, maybe it would be OK to show a warning when the refactoring is executed to tell the user to verify the result because code can be broken + document the known issues. I think that, in most cases, code won't be broken. But it's important for people to trust the safety of automated refactorings when they're touching Legacy Code (especially when there's no test yet and they try to get there).

Do you have an alternative suggestion that would make a first iteration not too hard to implement to get the value of this refactoring without risking to break people code without notice?

**Comment by OliverJAsh** [comment]
Yeah it's tricky. Unfortunately I don't have any better ideas, other than showing a warning to the user, like you say.

**Comment by OliverJAsh** [comment]
Ideally this code action would only appear when the cursor is on a function type, otherwise it would add noise in lots of other places where the action doesn't make sense. E.g. it could appear here:

```ts
fn(fn2)

```

but not here:

```ts
fn(string)
```

How can we do that? We will need to correspond type information to the AST nodes 🤔

**Comment by nicoespeon** [comment]
From the identifier we might be able to get the type indeed. We can get this with TS for example.

**Comment by OliverJAsh** [comment]
> We can get this with TS for example.

Yeah I just have no idea how to extract type information like that, do you?

**Comment by automatensalat** [comment]
If you want to tackle this you might want to check out the [Hocus Pocus](https://github.com/nicoespeon/hocus-pocus/) where @nicoespeon retrieves the type information for generating a new function. See [here](https://github.com/nicoespeon/hocus-pocus/tree/master/src/create-function-with-types)

**Comment by nicoespeon** [comment]
This one is old and still tricky to get right. I don't see we'll implement that in a foreseeable future, so closing it for now.
