### ISSUE TITLE
"Convert function declaration to expression or arrow function" (and vice versa)

### ISSUE THREAD

**Issue by OliverJAsh** [nicoespeon/abracadabra#113]
Hey @nicoespeon. I just watched [your fantastic workshop](https://www.youtube.com/watch?v=udNV7zPN1H8), thank you so much.

In the workshop you demonstrate a refactoring for converting function declarations to arrow functions. Do you think we could add something like this to Abracadabra?

We would probably want to support conversions both ways, between declarations and expressions. When converting to an expression, we should support both non-arrow and arrow formats.

`vscode-javascript-booster` has something along these lines:

- https://github.com/xsburg/vscode-javascript-booster/blob/c2f1d10a2c256e8f4765ab7e6dc88e8a6629fc26/server/src/codemods/convert-arrow-fn-to-regular-fn.ts
- https://github.com/xsburg/vscode-javascript-booster/blob/c2f1d10a2c256e8f4765ab7e6dc88e8a6629fc26/server/src/codemods/convert-fn-decl-to-arrow-fn.ts
- https://github.com/xsburg/vscode-javascript-booster/blob/c2f1d10a2c256e8f4765ab7e6dc88e8a6629fc26/server/src/codemods/convert-fn-expr-to-arrow-fn.ts

Although when I tried it [they seemed to lose TypeScript generics](https://github.com/xsburg/vscode-javascript-booster/issues/33). I'm sure Abracadabra could do a better job 😉

**Comment by nicoespeon** [comment]
Hey @OliverJAsh 👋 

Thanks for the kind words! And yes, that's funny I presented an example that's not even in the extension 😉 

That's totally do-able with Abracadabra. It's not hard to preserve types, we already have some TS-specific refactorings so there's tooling to deal with types.

The only gotcha I can think of is hoisting. This is valid:

```js
doSomething();

function doSomething() {}
```

This is not, because the function declaration isn't hoisted anymore, so it's used before it's declared:

```js
doSomething();

const doSomething = () => {};
```

The refactoring should check that there's no usage of the function above the function declaration, at least. If refactoring can't be made safely, it shouldn't be proposed (this is the way it works today, although in the future we could let the user know and deal with it instead).

For the record, Webstorm warns the user when the refactoring would be invalid:

![image](https://user-images.githubusercontent.com/1094774/85965406-9aaee500-b98a-11ea-81f9-0b0891f2e504.png)

**Comment by nicoespeon** [comment]
In case it's not clear: I think this would be a nice refactoring. 

We just need to do a good job with the edge case I mentioned so we don't break people code 👍

**Comment by OliverJAsh** [comment]
> should check that there's no usage of the function above the function declaration

Agreed! Thanks for the feedback.

I wonder how hard this will be to get right. E.g. this is easy to detect:

> ```js
> doSomething();
> 
> function doSomething() {}
> ```

But we wouldn't need to warn in this case, where the function is referenced before it's declared, but this would work without hoisting because it's not called until after the declaration:

> ```js
> function a() {
>   doSomething();
> }
> 
> function doSomething() {}
>
> a();
> ```

I guess the [ESLint rule `no-use-before-define` handles this](https://eslint.org/docs/rules/no-use-before-define), so we could take a look at how that works.

> would you like to try take a stab at it?

I would love to! Let me get back to you on this.

**Comment by OliverJAsh** [comment]
> I guess the [ESLint rule `no-use-before-define` handles this](https://eslint.org/docs/rules/no-use-before-define), so we could take a look at how that works.
> 
> >

Hmm, [it doesn't](https://eslint.org/demo#eyJ0ZXh0IjoiZnVuY3Rpb24gYSgpIHtcbiAgZG9Tb21ldGhpbmcoKTtcbn1cblxuZnVuY3Rpb24gZG9Tb21ldGhpbmcoKSB7fVxuXG5hKCk7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo1LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7Im5vLXVzZS1iZWZvcmUtZGVmaW5lIjoyfSwiZW52Ijp7fX19)—it still errors. What do you think we should do? Warn anyway?

**Comment by OliverJAsh** [comment]
Here's a start: https://github.com/nicoespeon/abracadabra/pull/114

**Comment by nicoespeon** [comment]
```js
function a() {
  doSomething();
}

function doSomething() {}

a();
```

Good point, I didn't thought about this one.

At this point, I hope there's something present in the AST that would help. If not, we might have to implement the logic that tells if the code is problematic or not.

I have some hope on the TS side because they do detect when there's a problem:

![image](https://user-images.githubusercontent.com/1094774/86123918-4dc13080-baa8-11ea-87ca-506feed48494.png)

So there's probably something that could help. Although we might have to introduce TS parser here to analyze the code for this one.

Thanks for the PR, I'll have a look at it this week 👍

**Comment by OliverJAsh** [comment]
If detecting this is difficult then we might have to do something similar to https://github.com/nicoespeon/abracadabra/issues/110—show a warning.

**Comment by nicoespeon** [comment]
Next steps: 
- reverse refactoring
- handling edge cases (we can wait for this to be raised before handling it)

**Comment by OliverJAsh** [comment]
> * reverse refactoring

TypeScript now provides this as a refactoring named "convert to named function", so I don't think there's any point to us doing this now?

> * handling edge cases (we can wait for this to be raised before handling it)

Do you remember what these were?

**Comment by nicoespeon** [comment]
As for TS, v4 do handle that indeed so it will arrive in VS Code soon (currently it's using v3.9.7). Likely next month.

**Comment by OliverJAsh** [comment]
Worth mentioning also that the TS refactoring doesn't support conversion from non-arrow function expressions, e.g.

```ts
const fn = function () {}
```

… if someone needs it, we can provide this as a custom refactoring, but this is far less common than arrow functions nowadays so it's not urgent.
