### ISSUE TITLE
Convert to arrow function misbehaviors

### ISSUE THREAD

**Issue by sluukkonen** [nicoespeon/abracadabra#159]
## Issue 1

Given 
```javascript
#!/usr/bin/env node

function test() {}
```

If I use "Convert to arrow function" on `test`, the result is

```javascript
#!/usr/bin/env nodeconst test = () => {};
```

## Issue 2

Given

```
// This is a comment.

function test() {}
```

If I use "Convert to arrow function" on `test`, the result is

```
const test = () => {}
```

Poof! The comment is gone!

## Additional information

- Version of the extension impacted: _v4.7.0_

**Comment by nicoespeon** [comment]
Thanks for reporting @sluukkonen, the examples were really helpful to reproduce!

I just fixed these 2 cases. It turned out the shebang one was a broader issue. It's likely that all refactorings would mess up the shebang, but not anymore 👍 

These will be part of the next release (which I'll do today, so very very soon).

**Comment by nicoespeon** [comment]
@all-contributors please add sluukkonen for bug
