### ISSUE TITLE
Make Rename Symbol work with any .vue files

### ISSUE THREAD

**Issue by leosdad** [nicoespeon/abracadabra#191]
## Is this request related to a problem? Please describe.

A very important (if not *the* most important) refactoring is Rename Symbol, which unfortunately does not work with .vue files.

## Describe the solution you'd like

You have described a possible to a way to do it here: https://github.com/nicoespeon/abracadabra/issues/133#issuecomment-725089062

**Comment by nicoespeon** [comment]
Hey @leosdad 👋 

Turns out this wasn't too hard to implement. A bit of refactoring and introducing a fallback was as smooth as I anticipated.

The UX is similar to what you can have with other files. The only thing is that I couldn't make the input box popup just below the renamed symbol. I don't see how to do that with VS Code API. If someone knows, please let me know 😄 

Here's how it looks like in action:

![2020-11-17 Screenshot-ITSgnxkI](https://user-images.githubusercontent.com/1094774/99482894-076f4f80-292b-11eb-87dd-e191777acc91.gif)

As you can see, it also triggers automatically after "Extract Variable", making this refactoring smoother too!

I covered all cases I could think of with tests. But I'm not working with Vue files every day. Please let me know if you encounter any issue with this feature 👍

**Comment by nicoespeon** [comment]
@all-contributors please add leosdad for ideas

Thank you @leosdad for suggesting this 👍

**Comment by nicoespeon** [comment]
I'll release this on Thursday, after our weekly pair-programming session with @fabien0102. So you won't have much to wait before you can use it 😉 🍷

**Comment by leosdad** [comment]
That's amazing, thanks a lot for your attention to this issue! I'm glad it wasn't hard to implement.

Thanks again for your speedy response.

**Comment by nicoespeon** [comment]
@leosdad I just created the release. It should be out there as v4.11.0.

Let me know if you find any edge case when using it. I hope/think that will be helpful!

**Comment by leosdad** [comment]
@nicoespeon , renaming works! It seems to convert all tabs to spaces, though. See below:

![2020-11-19_17-50-05](https://user-images.githubusercontent.com/7026091/99722814-fee45980-2a8f-11eb-959a-f7fc2b6d5651.gif)

Not a big problem, but it would be nice to keep the tabs if possible.

**Comment by nicoespeon** [comment]
@leosdad Oh snap! Thanks for telling, I'll create a bug issue to track this and see how to fix it.

**Comment by nicoespeon** [comment]
@leosdad after all this time, this is finally fixed! It will get shipped in the next release 😉

**Comment by nicoespeon** [comment]
@allcontributors please add leosdad for bugs
