### ISSUE TITLE
Toggle braces on statement

### ISSUE THREAD

**Issue by wmertens** [nicoespeon/abracadabra#211]
## Is this request related to a problem? Please describe.

While coding, I think "Oh I need to add braces to this statement now", and then I don't want to think about if I want to add braces to an arrow function or an if statement.

For removing braces, I think "I need to do brace management". So ideally, there's just a toggle command that I can put on a single shortcut.

When I see I made a mistake, I just undo and reposition my cursor to redo.

## Describe the solution you'd like

I'd like a brace toggle command to automatically add/remove braces to the nearest if block or arrow function.

**Comment by nicoespeon** [comment]
+1 for doing that

Also suggested by @detzt: enable this on other kinds of statements, such as for-loops, while, etc.

Note: it will be handy that the quick fix message makes it explicit which kind of statement we'll toggle braces on. Having a single toggle will simplify the UX and the source code.

**Comment by nicoespeon** [comment]
All add/remove braces refactorings have been consolidated into a single "Toggle Braces"

![toggle-braces](https://user-images.githubusercontent.com/1094774/126361500-6e53cd37-62fc-4b82-8f14-67d1258cf8c1.gif)

☝️ I would personally use `Alt ↵` to trigger the quick fix instead of clicking on the light bulb, it's faster. You can add a custom shortcut yourself if you want!

I will release this by the end of the week.

**Comment by nicoespeon** [comment]
@all-contributors please add wmertens for ideas
