### ISSUE TITLE
Don't prompt rename box if identifier can't be renamed (Vue examples)

### ISSUE THREAD

**Issue by PotatoesFall** [nicoespeon/abracadabra#212]
## Describe the bug

When I am in a .vue file and want to rename a variable using F2 or the command palette, **the prompt box for renaming opens up as expected**. I type in the new name, press Enter and nothing happens.

## How to reproduce

* Create new empty Vue3 project `vue create blablabla`
* Open App.vue and add some data() variable
* Attempt to change name using F2 or other
* --> nothing happens

## Expected behavior

I expect the variable's name to be changed, or there to be an error message if it is not possible.

## Additional information

- Version of the extension impacted: _v4.12.1_
- Using Windows 10 build 19041
- Other vue, js or editor related extensions:
  - prettier
  - vetur

Thoughts so far:
* Reinstalling the extension does not work
* Happens both on windows and wsl under windows
* Have not been able to attempt on linux (or on another machine)

**Comment by nicoespeon** [comment]
Thanks for reporting @PotatoesFall, I'll give it a look on Thursday 👍

**Comment by nicoespeon** [comment]
Hi @PotatoesFall 👋 

I wasn't able to repro on my side. Could you share with me the content of the file where you try to rename the variable?

With the file snippet I should be able to simulate what's going on. Thank you!

**Comment by nicoespeon** [comment]
@PotatoesFall I can't reproduce it on my side. It would be really helpful if you could put the content of the `.vue` file where rename doesn't work. That should help me repro and add a test for it.

**Comment by ex47** [comment]
@nicoespeon I believe I experience the same issue. Here's my file:

```
<template>
    <div class="word"><div class="typed">{{typed}}</div>{{remaining}}</div>
</template>
<script>
export default {
    name: 'Word',
    props: {
        wordToShow: String, 
    },
    data: function() {
        return {
            position: 0,
            word: this.wordToShow,
            length: undefined,
        }
    },
    mounted() {
        console.log("mounted "+ this.$options.name);
        this.length = this.word.length;
        console.log(this.length);
    },
    computed: {
        typed() {
            return this.word.slice(0,this.position);
        },
        remaining() {
            return this.word.slice(this.position);
        }
    }
}
</script>
<style lang="less" scoped>
.word {
    position: absolute;
    top: 0;
    left: 50%;
    display: flex;
    border: black 5px solid;
    background: black;
    color: #999;
    transform: translateX(-50%);
    .typed {
        color: #fff;
    }
}
</style>
```

If you need additional info - ask away.

**Comment by nicoespeon** [comment]
Thanks @ex47, that was helpful!

Indeed, what can be renamed is very limited. Basically, it won't consider anything besides the `<script>` so trying to rename a computed variable won't work. Also, any syntax that's Vue.js-specific won't be understood.

Unfortunately, I have no simple solution for this. That would require a deeper understanding of Vue.js AST to resolve the relations across each "block" (template, style, script). As this is not Abracadabra focus at the moment, I can't promise you to solve that anytime. I'm open to discuss how this could be resolved though. I think we first need abstract the AST parsing from the rest of the code first, otherwise that will be challenging to overcome 🤔 

I note that something is confusing though: the rename input is triggered although it has no effect, feeling like a bug when I'd consider that as a "missing scenario" (so more of an enhancement). I'll fix that so renaming isn't suggested where it can't be done, make it clearer that's something not handled yet.

**Comment by nicoespeon** [comment]
Here it is. Not _ideal_, but at least it explains the current behavior.

![CleanShot 2021-09-04 at 12 25 14](https://user-images.githubusercontent.com/1094774/132101690-789cecb9-a339-4c66-8352-3f3686c6a675.png)

Again: supporting Vue files isn't a priority because I'm not a Vue developer myself. I made it possible to use Abracadabra refactorings in Vue files so life is a bit better, but there are some Vue-specific stuff that require a deeper understanding of the problem (e.g. computed identifiers used in `<template>` for instance).
