### ISSUE TITLE
New refactoring: React proptypes to TypeScript interface

### ISSUE THREAD

**Issue by Talor-A** [nicoespeon/abracadabra#246]
## Is this request related to a problem? Please describe.

I'm currently in the middle of a large react codebase refactor from js => ts. Most of the old components have proptype definitions, and a tool to automagically create a new typescript interface based on those definitions would be crazy helpful.

there's already an extension that does something similar [here](https://marketplace.visualstudio.com/items?itemName=mohsen1.react-javascript-to-typescript-transform-vscode), by leveraging the typescript compiler, but hasn't been updated in a while and it's quite buggy in my experience. plus, the refactor of proptypes => interface is just one step in the conversion, and can't be separated from the rest of the modifications made by the extension.

it could also work similar to [this](https://github.com/Agreon/styco) extension, which creates styled components

## Describe the solution you'd like
- `cmd+.` on a react component declaration
- a refactor suggestion appears: "create interface from prop types"
- a new interface is generated.

## Example:
before: 
```tsx
export const MyComponent = ({ name }) => (
	<h1>hello, {name}!</h1>
)

MyComponent.propTypes = {
	name: PropTypes.string.isRequired
}
```
after:
```tsx
export interface MyComponentProps {
	name: string;
}

export const MyComponent = ({ name }: MyComponentProps) => (
	<h1>hello, {name}!</h1>
)
```

## Additional context

a similar refactoring to move `defaultProps` to default function parameters would be awesome as well, and possibly less involved since it doesn't involve parsing type information

**Comment by nicoespeon** [comment]
Hey @Talor-A, thanks for suggesting!

Indeed, this would categorize as refactoring and I don't think it would be too complex to implement. The core of it would be to parse the propTypes definitions into the valid interface, but there is no soooo many cases to handle.

I can't commit to doing it soon for the moment as I'm already working on other issues at the moment. If you're willing to tackle it though, I can probably get you started.

**Comment by nicoespeon** [comment]
Hey @Talor-A 👋 

After all this time, I thought about this with @fabien0102.
It turns out there's a codemod now to perform such a transformation: https://github.com/mskelton/prop-types-to-ts

It's more appropriated since you'd likely want to do that at scale, not component per component.

For others who might get into this issue, note that you can also use the `prop-types` package to infer props from the `propTypes`: https://fettblog.eu/typescript-react/prop-types/#inferring-prop-types
It may be useful if you need to keep the `propTypes` for runtime validation (e.g. you're building a public library).

**Comment by Talor-A** [comment]
Thanks for the update! That’s a great solution.
