### ISSUE TITLE
Convert ternary to if-else - not clear when it should work or not

### ISSUE THREAD

**Issue by chipbite** [nicoespeon/abracadabra#264]
## Tried convert ternary to if-else, did not work

Clarify what cases the refactoring works for? 

Did not work for this:
```let publishesNeedingLink = args.forcelink ? page.directives : page.findPublishesLackingLinkInPage();```

_(clarification of the line: assignment of a local array variable using a boolean to decide between an instance array or an instance method returning array)_

## Screenshots

This is crap code, but here is the message I got:
![image](https://user-images.githubusercontent.com/559199/112325962-67e51380-8cb4-11eb-8fa8-5c7740215613.png)

BR! /marcus

**Comment by ZakMiller** [comment]
![2021-03-27 17 52 48](https://user-images.githubusercontent.com/18072671/112735944-7423d780-8f25-11eb-828f-14eb778a1319.gif)

I didn't reproduce the same issue, but I was unable to refactor the same line with the whole thing highlighted. I was able to reproduce it with a cursor on the line.

**Comment by ZakMiller** [comment]
I have a test ready and I'm happy to pick this up depending on what we decide to do.

**Comment by nicoespeon** [comment]
Thanks for reporting and thank you for the analysis @ZakMiller 

I don't have time to read it in details now, but just want to let you know that I'll do it by Thursday 😄

**Comment by nicoespeon** [comment]
@ZakMiller you did a great root-cause analysis, the problem was with the selection indeed.

The reason is that the ternary is a node that was nested inside the selection, and we don't usually support that. Instead, the selection has to be inside (or equal to) the node to apply the refactoring. It has become a standard indeed. We could revisit this.

Although I'm not sure yet that "refactor the first case from the selection" is something I'd like to see happen 🤔 

I'll put more thoughts into this. "Not now" I'd say.

However, I added a special condition for this so we support ternaries assigned to a variable. This will work now (well, with the next release of the extension at least).

**Comment by nicoespeon** [comment]
@all-contributors please add chipbite for bug

**Comment by nicoespeon** [comment]
@all-contributors please add ZakMiller for ideas
