### ISSUE TITLE
[Typescript] New Refactoring: Declare return type explicitly

### ISSUE THREAD

**Issue by automatensalat** [nicoespeon/abracadabra#272]
## Is this request related to a problem? Please describe.

Typescript allows to omit the return type declaration of a function signature:

```ts
// this function...
function add(a: number, b: number): number {
  return a + b;
}

// can be written as:
function add(a: number, b: number) {
  return a + b;
}
```

I often start out without an explicit return type, but on a case-by-case basis I want to declare the return type explicitly on a function to document explicitly what a function returns. To do this I now hover my mouse cursor above the function declaration to see which type TS infered and type this down manually. Naturally I'd like to reduce this manual work as much as possible.

## Describe the solution you'd like

I'd like Abracadabra to introduce a new refactoring that is triggered on a function declaration in a TS file, when the function does not explicitly declare a return type. The refactoring could be called "Declare Return Type Explicitly". When executed, the refactoring would get the infered type from TS and add it to the function declaration (i.e. it converts the second form of the example above into the first form).

**Comment by nicoespeon** [comment]
Love it, I can definitely see the use case. 

It will help me deal with legacy code that has no explicit return type. Making it explicit helps me change the code and get instant feedback if the return type isn't compatible anymore. TS will complain right here instead of doing it where the function is used. For public API, making return types explicit is a must IMO.

**Comment by chrstnbrn** [comment]
@automatensalat @nicoespeon 
TypeScript already has a "Infer function return type" refactoring:
![refactoring](https://user-images.githubusercontent.com/11138584/116444946-975be280-a855-11eb-888a-8c0eac47428a.gif)

However it looks like this is currently only available in the refactor menu and not as a quick fix.

**Comment by nicoespeon** [comment]
Oh my that's awesome! As for it not being suggested in quick fixes, it seems to come from here: https://github.com/microsoft/TypeScript/issues/42993

I guess they could improve this by only suggesting it:
- if the cursor is on the function signature (not the body)
- if the function has no return type already

I'll check if there's an issue for that already. Will create one otherwise. 

In any case, I think it doesn't worth implementing this in Abracadabra if it's already provided by TS (since this would only be available for TS code anyway).
