### ISSUE TITLE
The `Inline` refactoring is abusing lambda definitions scope

### ISSUE THREAD

**Issue by gurdiga** [nicoespeon/abracadabra#316]
## Describe the bug

The `Inline` refactoring replaces every identifier in the code block even if that identifier:
1. is a parameter of a lambda function declaration;
2. is a scoped identifier inside the lambda function.

## How to reproduce

On the following snippet invoke the `Inline` refactoring for the `title` constant on the first line:
```ts
const title = document.title;
const lambda = (title: string) => title.length > 0;

return {title: title}
```

The unexpected result (broken code):
```ts
const lambda = (document.title) => document.title.length > 0;

return {title: document.title}
```

## Expected behavior

```ts
const lambda = (title: string) => title.length > 0;

return {title: document.title}
```

## Additional information

- Version of the extension impacted: v5.3.1
- VSCode version: 1.57.0
- TypeScript version: 4.3.2
- Many thanks for this useful thingy! 🙏😊

**Comment by nicoespeon** [comment]
Thank you for the detailed bug report @gurdiga 🙏 

I used your snippet to create a test case and fix this. The root cause was that asking "is this a function declaration" would not consider "arrow function expressions". So I fixed that, which should lead to future improvements too!

So thank you for helping me making this more robust 💪 

I'll ship the fix in the next release, by next week.

**Comment by nicoespeon** [comment]
@all-contributors please add gurdiga for bug
