### ISSUE TITLE
'Convert var to const' & 'Convert var to let'

### ISSUE THREAD

**Issue by eJaimesBlueRoster** [nicoespeon/abracadabra#318]
I was looking for a plugin that refactors 'var' into let or const, I like the  ALT Enter, hotkey option, I was wondering if it was possible for you to include this feature.

Thanks for your time and effort on this plugin, Great work.

Regards

**Comment by nicoespeon** [comment]
Hey @eJaimesBlueRoster 👋 

That's a good suggestion. We already have [Convert let to const](https://github.com/nicoespeon/abracadabra/blob/master/REFACTORINGS.md#convert-let-to-const) so I don't see why we wouldn't provide "Convert var to let/const" either.

How I see it:
- If the variable is re-assigned later, convert to `let` (`const` would break the code)
- If the variable is not re-assigned, ask the user to select `const` or `let` (`const` is the default)

The only risk of this refactoring is that the scope of `var` is different than `let`/`const`. It may break the code in some scenario, but I guess we could detect that and prevent the refactoring in this case 🤔

**Comment by nicoespeon** [comment]
Thinking about this one a bit: it's a good candidate for a first issue. If someone is interested in implementing a new refactoring, I'd suggest you have a look at this one.

Just let me know here and I can guide you in the implementation.

This will also be helpful: https://github.com/nicoespeon/abracadabra/blob/master/CONTRIBUTING.md

**Comment by nicoespeon** [comment]
Hey!

Gave more thought to this specific one with @fabien0102. We realized that if you are in such a situation, you should better fix it across your codebase directly. ES Lint can do that with the `no-var` rule + `--fix` option: https://eslint.org/docs/rules/no-var

Unlike other Abracadabra's refactorings, it's not like you are about to switch back and forth with `var`. It's an old code pattern you probably want to fix at once, instead of manually converting.
