### ISSUE TITLE
New Refactoring: Remove Braces from If Statement

### ISSUE THREAD

**Issue by nicoespeon** [nicoespeon/abracadabra#33]
## Is this request related to a problem? Please describe.

It's the reverse of #24

I prefer to use one-liner If Statements to write guard clause.

```js
function doSomething() {
  if (!isValid) return;

  // … rest of the code
}
```

Sometimes, the guard clause is implemented with braces:

```js
function doSomething() {
  if (!isValid) {
    return;
  }

  // … rest of the code
}
```

I'd like to simply remove braces with a quick fix, so it will take 2 keystrokes. Without that, I have to:
- put the cursor after the closing brace
- remove the closing brace
- put the cursor after the opening brace
- remove the opening brace
- remove the remaining spaces to inline the return next to the if

## Describe the solution you'd like

Given:

```js
function doSomething() {
  if (!isValid) {
    return;
  }

  console.log("Something");
}
```

When I trigger the refactoring on the If Statement node,

Then I want:

```js
function doSomething() {
  if (!isValid) return;

  console.log("Something");
}
```

## Additional context

It's a similar refactoring than _[Remove Braces from Arrow Function](https://github.com/nicoespeon/abracadabra/tree/master/src/refactorings/remove-braces-from-arrow-function)_. 

You can use `yarn new` to help you bootstrap the refactoring.

I'm here to help.

**Comment by automatensalat** [comment]
Hey, I use this plugin in my everyday work and I want to contribute with some refactorings at some point. To get to know how the plugin works I started working on this particular refactoring here. I have it working, however I have some failing test cases because I cannot control or do not understand how the formatting works.

Consider the example of your proposed solution: 
```ts
  if (!isValid) {
    return;
  }
```
Rather than putting the `if` and the `return` in one line my implementation will change the code to 
```ts
  if (!isValid)
    return;
```
Which, of course, is also a valid solution. So my questions are
1) Should we care about the output formatting or force a particular formatting style? 
2) If yes, how should we go about achieving this? Since in the refactoring we're manipulating an Abstract Syntax Tree which afaik only deals with the structure of a piece of code I currently don't see a way to influence the formatting at all. Perhaps I'm overlooking something.

Any pointers would be welcome.

**Comment by nicoespeon** [comment]
Hi @automatensalat 👋

First of all, thank you for your help, it's very much appreciated!

> Should we care about the output formatting or force a particular formatting style?

It would be fine to have the feature working first, and then we optimize from the feedback we received. Thus, if you have a valid solution that generates this output, you can already open a PR.

If people use some tooling to prettify their code, it may not even matter for them.

> If yes, how should we go about achieving this?

As a user of the extension, I would expect the result to be on a single line if it has no braces. So I'll try to find a solution to this.

As you said, you can't achieve this with the AST. I don't think we could configure it so it produces a one-liner.

What we could do is transform the generated code string, after the AST transformation and before we write it back to the editor. We could detect this pattern (if + new line return) and replace the new line with a single space. The tricky part would be to change only the transformed `if`.

I did something a bit similar here: https://github.com/nicoespeon/abracadabra/blob/5cc121f2b6e25682380301d0b910c616c61e5e94/src/refactorings/flip-if-else/flip-if-else.ts#L19-L23
