### ISSUE TITLE
Syntax error when TypeScript <type-cast> syntax used

### ISSUE THREAD

**Issue by nene** [nicoespeon/abracadabra#332]
I'm working in a codebase with that uses `<Type>` instead of `as Type` syntax for typecasts.

Whichever refactoring I try, it fails with error:

> 😅 I'm sorry, something went wrong: I can't build the AST from the source code. This may be due to a syntax error that you can fix. Here's what went wrong: Unterminated JSX contents. (108:22)

<img width="461" alt="Screenshot 2021-07-02 at 17 01 04" src="https://user-images.githubusercontent.com/118201/124286003-2a1b4500-db57-11eb-9a37-07270cb8618d.png">

When I replace all uses of angle-bracket syntax with `as` in a file, the refactoring works. But that's really not a feasible option for me.

## Additional information

- Version of the extension used: _v5.4.1_

**Comment by nicoespeon** [comment]
Hey @nene!

Thanks for reporting. That's strange because the extension does support type-cast syntax. But it says that it can't parse the source code indeed. It seems that it understands the type-casts as being JSX statements 🤔 

Could you share a small snippet of code that would repro the issue? That would help me investigate what's going on. I suppose there's an edge-case that we're not supporting yet, but I can't find what this would be.

**Comment by nicoespeon** [comment]
Closing because it's old and I can't repro without more details.
