### ISSUE TITLE
Lightbulb suggestion action functionality differs from keyboard shortcut action functionality

### ISSUE THREAD

**Issue by vfonic** [nicoespeon/abracadabra#350]
## Describe the bug

I wanted to add a keyboard shortcut for one refactoring that I use a lot: convert function to arrow function (`abracadabra.convertFunctionDeclarationToArrowFunction`).

If I execute the suggestion from the lightbulb, the function gets properly converted. However, if I try to execute the keyboard shortcut, while having the keyboard carret on the same position like before, I get the following error message:

> I didn't find a function declaration to convert from current selection 🤔

## Expected behavior

The function gets converted to arrow function.

## Screenshots

Here's a screen recording:

https://user-images.githubusercontent.com/67437/127483555-803d49ca-f43f-45b1-a625-802ed1e1074a.mov

(to revert the change I just use "undo" CMD+Z)

## Additional information

  - Version of the extension impacted: _v6.0.0_
  - macOS
  - VS Code 1.58.2

_🧙‍ Add any other context about the problem here._

Keyboard binding:

```json
{
    "key": "alt+a",
    "command": "abracadabra.convertFunctionDeclarationToArrowFunction",
    "when": "editorTextFocus"
  },
```

**Comment by nicoespeon** [comment]
Thanks for the detailed report @vfonic 

It turns out the suggested "Convert to arrow function" in the quick fix is _not_ suggested by Abracadabra. It's VS Code directly (they're starting to propose more and more refactoring). You can tell because Abracadabra's lightbulb suggestions are suffixed with a little `✨`

Anyway, I investigated _why_ Abracadabra wasn't supporting this scenario. Turns out we forgot to handle "Function Expression". I'll spare you the details, but I implemented it now!

I'll ship it in the next release, likely next week 😄

**Comment by nicoespeon** [comment]
@all-contributors please add vfonic for ideas

**Comment by vfonic** [comment]
@nicoespeon you, sir, are a legend! Thank you! :)
