### ISSUE TITLE
Extract a variable on a function with types inferred

### ISSUE THREAD

**Issue by fabien0102** [nicoespeon/abracadabra#44]
## Describe what's missing

With the following snippet as example:
```tsx
import PanelGroup from "react-panelgroup";
import React from "react";

const MyAwesomeComp: React.FC = () => {
  // ...

  return (
  <PanelGroup onUpdate={([sidebar]) => setSidebarWidth(prev => sidebar.size || prev)}>
    {/* Implementation details… */}
  </PanelGroup>)
};
```
If I try to "Extract variable" the `onUpdate` function in a typescript context, the refactor will not be as good as expected due to the lack of types.

![image](https://user-images.githubusercontent.com/1761469/67461389-84070000-f63d-11e9-8e88-30d390a57ae2.png)

Indeed, when a function is defined as props, the types inferred, but not when it's extracted.

## Expected behavior

In a perfect world, I would like this after the "Extract variable" on this kind of case.

```tsx
import PanelGroup, {PropsTypes} from "react-panelgroup";
import React from "react";

const MyAwesomeComp: React.FC = () => {
  // ...

  const extracted: PropsType["onUpdate"] = ([sidebar]) => setSidebarWidth(prev => sidebar.size || prev)
  return (
  <PanelGroup onUpdate={extracted}>
    {/* Implementation details… */}
  </PanelGroup>)
};
```

## One step further

In an ever better world, what I really would like is to have a `Extract in useCallback`!

## Additional information

- Version of the extension used: _v0.9.0_

**Comment by nicoespeon** [comment]
So, we discussed this one IRL. In summary:

1. That would be awesome. Getting the inferred type and setting it for TS files means less manual work for people, that's great.

2. To do so, we need to get the inferred type. I don't see how to do that without having solve one of the main current issues: Abracadabra doesn't resolve things outside of the file yet. Until this is solved (and that would be a whole new level for the extension), this issue can't be solved.

Thus, because there's a very complex pre-requisite, I don't think this will be implemented soon.

I'm closing the issue for that reason. I'm not flagging it as "wontfix". It might pop-up again in the future. But for the moment, it's not something we can do.
