### ISSUE TITLE
Expand selection to region with nearest possible refactoring

### ISSUE THREAD

**Issue by kbysiec** [nicoespeon/abracadabra#48]
## Is this request related to a problem? Please describe.

Trying to refactor there is a necessity to select or put the cursor on the exact place to see the available refactorings. I know that it is a default for VSC built-in refactoring but it is problematic/ irritating.

## Describe the solution you'd like

It would be perfect if there will be a command which will combine two steps:
1. Expand selection to the region with nearest possible refactoring if there is not currently already done
2. Show available refactorings for the selected region/code

The feature I mean is implemented in that way in another extension: [Intelli Refactor](https://marketplace.visualstudio.com/items?itemName=ypresto.vscode-intelli-refactor)

## Additional context

Thank you for great extension!

**Comment by kbysiec** [comment]
I have just noticed I can use the feature from the extension I mentioned. After selection, it shows all available refactorings, from abracadabra as well.

**Comment by nicoespeon** [comment]
Hi @kbysiec and thanks for the kind words 👋 

Indeed, Abracadabra is a bit more flexible than VS Code built-in refactorings: it will work as long as your cursor is inside a code that can be refactor.

I didn't knew about Intelli Refactor, thanks for mentioning. Thus, I'm not sure if the problem was solved because it's Abracadabra default behavior or if it combines well with this other extension. Anyway, I'm glad it works as you expect now! 😄
