### ISSUE TITLE
Extract Interface does not work with export default keywords

### ISSUE THREAD

**Issue by kevintechie** [nicoespeon/abracadabra#487]
## Describe the bug

When using the Extract Interface command on a class with the `export default` keywords, abracadabra displays the "I didn't find a class to extract the interface from current selection 🤔" error message notification. If the `default` keyword is removed, the extraction is successful.

## How to reproduce

Given the following code:

```TypeScript
export default class Foo {
  constructor(param: string) {}

  bar(): number {
    return this.param.length;
  }
}
```
1. Place cursor at start of class.
2. Use `Abracadabra: Extract Interface` from the command palette.
3. Observe error notification.

## Expected behavior

Should extract the interface as when `default` keyword is not used.

## Additional information

- Version of the extension impacted: _v6.9.1_

**Comment by nicoespeon** [comment]
Hey @kevintechie, thanks for reporting!

The funny part is that we solved the issue for named exports… but that wasn't generic enough to cover default exports too. It turns out exported statements are lacking location information on the node, so the logic can't execute properly. We work around that by picking the parent node location (= the export statement).

Anyway, this is fixed and will be part of the next release. Big thanks ❤️

**Comment by nicoespeon** [comment]
@all-contributors please add kevintechie for bugs

**Comment by kevintechie** [comment]
Thankyou. This extension is really great.
