### ISSUE TITLE
`Move Statement Down` / `Up` should work with JSX props

### ISSUE THREAD

**Issue by zardoy** [nicoespeon/abracadabra#493]
In a word it should work with this:
```ts
const css = String.raw

const Component = (...inputProps) => (
    <input
        css={css`
            :active {
                color: darkred;
            }
            :hocus {
                color: red;
                background: white;
            }
        `}
        tw="w-full py-1 text-lg border border-none rounded"
        {...{
            a: 5,
            b: 6,
            ...inputProps,
        }}
    />
)
```

It works correctly only within object, (also I was surprised that it can't move `...inputProps`).
WebStorm can do this, however WebStorm thinks that spread prop (`{...{`) is JSX expression and moves it out of `<input>` element, which is obviously incorrect.

Also I wonder what do you think about having integration with third-party extensions? What if i want to move `:active` below `:hocus`?

I think we should do a way to let other extensions first do the action and only then do it oursevles. I can think about it.

**Comment by nicoespeon** [comment]
Agree, Move Statements should cover JSX props too 👍 

Unfortunately, we can't easily interact with other extensions. AFAIK, there is no "event bus" or something in VS Code API that would allow extensions to trigger events and subscribe to others. I think we can trigger commands from another extension with their ID, but that's not very scalable. The responsibility should be reversed.

Thus, I don't have much hope for moving the `:active` and `:hocus` here, because that's just a template string content from Abracadabra's point of view 🤔

**Comment by zardoy** [comment]
Oh sorry, I just opened this issue in a rush and now I think it'd be much easier to not track plugin support here. Lets just track support for moving JSX props only.

**Comment by zardoy** [comment]
I opened #495 for this, let me know what you think.
