### ISSUE TITLE
Refactor repeating statements into an array of differing arguments with looping over

### ISSUE THREAD

**Issue by cibolog** [nicoespeon/abracadabra#496]
```js
if ("pencil" in box) {draw(box.pencil.color)} 
if ("pen" in box) {draw(box.pen.color)} 
if ("crayon" in box) {draw(box.crayon.color)} 
```
should become something like
```js
const boxItems = ["pencil", "pen", "crayon"]

boxItem.forEach(item => {
    if (item in box) draw(box[item].color)
});
```

**Comment by nicoespeon** [comment]
Hey @cibolog 👋 

Thanks for suggesting. I won't implement this refactoring into Abracadabra because it seems very, very specific to me. You need to:
- have consecutive `if` with the `in` operator
- have the body of the if statements are duplicated

Variants would work too (eg. `if ("pencil" in box || "pen" in box)` and could be refactored, but I never really encounter this pattern in the codebases I've worked with.

I feel it would take more time to implement than it saves.

If that's something common in your codebase and you want to fix that at scale, I suggest you check out a codemod like [jscodeshift](https://github.com/facebook/jscodeshift). It will allow you to create a custom automated refactoring and run it across your codebase. That's very handy for when you deal with transformations that are specific to your codebase.
