### ISSUE TITLE
Show inline command in code actions

### ISSUE THREAD

**Issue by brunnerh** [nicoespeon/abracadabra#546]
## Describe what's missing

Inline is not shown as a code action on symbols (which is why I thought the feature does not exist at first).

## How would it work

Show action if command is available.

## Expected behavior

Command is listed along the other available code actions.

## Screenshots

```js
const x = 42;
const y = x * x;
```

Open code actions on `x`:
![image](https://user-images.githubusercontent.com/834235/158026611-b5831c03-c765-4bf0-8dc4-a06a20bb621e.png)

## Additional information

- Version of the extension used: _v6.12.0_

**Comment by nicoespeon** [comment]
That's a good point. Discoverability is important.

I was concerned because it would be suggested on _every_ variable. But since we can decide to show/hide these suggestions now, I guess it makes sense to enable it by default. Advanced users can always customize what they want to be suggested 👍 

I'm gonna do that for the other refactorings. Basically, all the ones bound to a shortcut today:https://github.com/nicoespeon/abracadabra/blob/main/REFACTORINGS.md#the-essentials

**Comment by nicoespeon** [comment]
There we go! That will be part of the next release.

![Inline](https://user-images.githubusercontent.com/1094774/161341060-729b0ea1-1d43-484e-9ec4-917ad0be61c1.png)

**Comment by nicoespeon** [comment]
@all-contributors please add brunnerh for ideas
