### ISSUE TITLE
Shortcut conflict

### ISSUE THREAD

**Issue by OliverJAsh** [nicoespeon/abracadabra#57]
First of all, thank you for this great extension! ❤️ 

## Describe what's missing

One shortcut built-in to VS Code which I frequently use is command + shift + down/up, to select from the cursor to the start/end of file.

Unfortunately this extension defines a shortcut which conflicts with this. I can probably reconfigure the extension to avoid this conflict, but I thought I would file an issue in case this effects other users. Perhaps we could replace the default shortcut with one that isn't already being used? 😄

**Comment by nicoespeon** [comment]
Hi @OliverJAsh and thanks for the kind words!

Sorry for this one, it has been reported and fixed (https://github.com/nicoespeon/abracadabra/issues/51), but I didn't released the fix so the problem was still here.

I just published a new release, so the default stops clashing: https://github.com/nicoespeon/abracadabra/releases/tag/2.0.0

The new shortcuts are a bit less convenient, but all the convenient ones were taken. So it would be `Alt + Shift + U / D`.

Let me know what are the features you use the most and the things you'd like to improve. I always like to hear from different use-cases than mine 😉

**Comment by OliverJAsh** [comment]
I'm using 2.0.0, but it looks like the (default) keyboard shortcut remains the same?

![image](https://user-images.githubusercontent.com/921609/70903840-b0187f00-1ff7-11ea-9824-76f1991af9be.png)

**Comment by OliverJAsh** [comment]
Ah, so the new shortcut conflicts with the built-in shortcuts for "copy line down/up".

**Comment by nicoespeon** [comment]
@OliverJAsh oh, I didn't realized you're on Mac, so you get the other shortcut: `⇧ ⌘ ↑/↓` 

So, this one didn't changed. The conflict I mentioned was on Windows/Linux, because there's no "Command" key I could use.

Indeed, I never used `cursorTopSelect` and `cursorBottomSelect`, so I didn't realized it conflicts on Mac OS too. I'll apply `Alt ⇧ U/D` to Mac too, so it doesn't conflict with any default shortcut 😁

**Comment by nicoespeon** [comment]
I'll publish the new version with the fix during the week 😉

**Comment by OliverJAsh** [comment]
Won't this still conflict? 🤔 

![image](https://user-images.githubusercontent.com/921609/70923231-78bdc880-201f-11ea-9ddd-c32a38e61d44.png)

**Comment by nicoespeon** [comment]
@OliverJAsh nope, it will be `⇧ ⌥ U` and `⇧ ⌥ D` on Mac too, so we should be fine (at last!) 😁
