### ISSUE TITLE
Convert function to arrow function prevents valid refactoring

### ISSUE THREAD

**Issue by brunnerh** [nicoespeon/abracadabra#633]
## Describe the bug

Invoking the refactoring can give a false positive error of:

> I'm sorry, I can't convert this function declaration, it's used before 😅

## How to reproduce

```js
for (const [id, path] of scripts)
	document.querySelector(id)
		.addEventListener('click', () => run(path));

function run(path) {
	// ...
}
```

Invoke `Convert to arrow function` on `run`.

## Expected behavior

Conversion is executed, possibly with a warning in case the deferred nature of the call cannot be determined easily.

## Screenshots

N/A

## Additional information

- Version of the extension impacted: _v6.14.4_

**Comment by nicoespeon** [comment]
Hey @brunnerh 👋

Thanks for your patience. I was quite busy these past weeks. And thanks for reporting!

To be transparent, this was something I was expecting to come up at some point. The detection was a bit naive—good enough in most cases, but not for such a situation.

I say "was" because I made it better, thanks to you! So this will now be working, along with other patterns. I don't promise I got 100% of them, but that should be much more than today.

Also, I realized it was a bad UX to suggest a refactoring you can' make (duh!). We usually don't, but this one slipped through the cracks it seems. So this is fixed too: if it can't be run, it won't show up. That should be _slightly_ better too. 

As for the suggestion of "doing it anyway with a warning", I have a _meh_ feeling about it. It could be nice, but I think we can do better. Actually, I would rather have people report patterns that don't work, so we can improve the refactoring again and again. I'm worried that such an escape hatch wouldn't be great and would not push people to report situations that don't work like today.
