### ISSUE TITLE
Better contribution guide

### ISSUE THREAD

**Issue by dutzi** [nicoespeon/abracadabra#65]
Hey!

I'm trying to contribute to this extension, but couldn't figure out how can I make changes in Abracadabra's code and see them live within the Extension Development Host (EDH). I tried running Webpack in watch mode, but then the EDH wouldn't start. I tried in regular build (yarn run build), but then I couldn't see the changes in the EDH until I restart webpack.

**Comment by nicoespeon** [comment]
Hi @dutzi, thanks for reporting! It's very helpful for me to get your feedback on this.

What if you press `F5`. It should build the project and launch the EDH. 

![](https://user-images.githubusercontent.com/1094774/71781462-90112580-2fcf-11ea-97d5-ac55abeb2bc8.png)

However you're right: I didn't manage to get a proper watch mode working. So I usually click on the reload button after I changed code to recompile and see the changes in the EDH.

![](https://user-images.githubusercontent.com/1094774/71781483-cea6e000-2fcf-11ea-8e3b-420b45dff1ce.png)

It's not ideal, but not a big issue to me since I don't use the EDH very often thanks to the unit tests (I spend most of the dev time using the tests to implement the feature, unless I'm working on a specific VS Code UX).

Let me know if it works… or not, so I could update the CONTRIBUTING.md to clarify the process and helps further contributors 👍

**Comment by dutzi** [comment]
Yes, after submitting the comment I played around with it a bit more and figured out the right way to approach this is using unit tests :)

**Comment by nicoespeon** [comment]
@dutzi Is there a way I could improve the CONTRIBUTING.md file to explain this better before hand? What would have helped you ramping up better?

**Comment by nicoespeon** [comment]
@dutzi thanks to your feedbacks I added more details on these points in the Contribution Guide: https://github.com/nicoespeon/abracadabra/blob/master/CONTRIBUTING.md#debug-locally

I think that covers what was not clear. Thus, I'm closing the issue.

Don't hesitate to re-open if you see specific information that would be helpful and missing.

**Comment by dutzi** [comment]
Sorry for disappearing, I hate being that guy.

I guess this was a case of not thoroughly reading the guidelines, on my part. They make sense now when I'm reading them.

**Comment by nicoespeon** [comment]
Everything is fine, no worry! 
Thank you 👍
