### ISSUE TITLE
Relatively high extension activation time

### ISSUE THREAD

**Issue by drewbitt** [nicoespeon/abracadabra#776]
Abracadabra, of my 30+ extensions currently running, takes the longest to activate by far.

487ms vs. the next highest of 161ms 

![image](https://user-images.githubusercontent.com/26885897/207391224-4d12525f-90e7-4916-a959-9d17ce97582a.png)

I'd love to see an improvement on activation time to bring it more in-line with the rest of the extension ecosystem.

**Comment by nicoespeon** [comment]
Good point @drewbitt. It has been a while since I checked the activation time and there are certainly some perfs improvements to be made today 👍

**Comment by tjx666** [comment]
One of the simplest way to improve performace it to upgrade the typescript target. 
All of my own extension only support latest 3 version vscode. So I can usr the latest vscode api and set tsc target to latest.

**Comment by nicoespeon** [comment]
I had a quick look here and have a few updates:

1. Actually, lower than 500ms is still a decent startup activation time. It depends on the nature of the extension. A quick look at my extensions shows me that some take much longer: 
![startup](https://user-images.githubusercontent.com/1094774/210081887-429d27b2-174a-4472-83d4-5237a0c7e1a5.png)
2. I upgraded the version of TS, VS Code, and node of the extension. Indeed, that may help a little bit. Although we were using pretty recent stuff already.
3. The activation time is relatively long because the extension registers all 45+ refactorings when it activates, so they are available to the editor. I'm not sure how to optimize this yet, but that seems reasonable to me.

However, that made me realize something: it's fine for the extension to take 500ms, or even 2s to be ready. But it should NOT delay the editor startup!

Therefore, I delayed the activation of the extension. It doesn't activate right when VS Code starts anymore. Instead, it activates [after it has fully started](https://code.visualstudio.com/api/references/activation-events#onStartupFinished). Hence, it still takes some time to do so, but it will be done in the background after your editor is ready to be used.

That should make your VS Code faster to load. Yet, you probably won't notice that the refactorings are available only a few seconds after the editor is ready 😉

It will be part of the next release!

**Comment by tjx666** [comment]
Another simple way to much improve the activate time is to using dynamic import. you can define https://github.com/nicoespeon/abracadabra/blob/main/src/refactorings/add-numeric-separator/index.ts#L9 to function and use dynamic import to import it.

**Comment by tjx666** [comment]
@nicoespeon I see you upgrade the @types/vscode to 1.72. VSCode 1.72 using the node 16. Node16 support syntax all ES2021, why not upgrde tsconfig target to ES2021?

**Comment by nicoespeon** [comment]
@tjx666 no reason to NOT do it, so let's do that! Thanks for the suggestion 👍

**Comment by drewbitt** [comment]
I am not benchmarking much of any performance improvements but the later activation helps. Thanks!

**Comment by tjx666** [comment]
@nicoespeon You can much improve the speed by dynamic import like https://github.com/tjx666/vscode-fe-helper/blob/master/src/extension.ts#L26

dynamic import one refactor code util you call the refactor.

**Comment by nicoespeon** [comment]
@tjx666 thanks for the suggestion, it's a great one!

Not sure it won't work though. Currently, all refactorings are exposed via Action Provider (aka Quick Fixes, the VS Code lightbulb 💡 ). That means we need them all so we can evaluate which ones should be suggested depending on where your cursor is.

But the improvement I made to delay the start of the extension should have fixed any problem. It doesn't really matter if it takes 650ms to load since it will only happen after VS Code has started.

**Comment by tjx666** [comment]
As the refactoring count grow, the delay will also grow.
In fact, using dynamic import to import the command logic should always be done at this project start.

**Comment by nicoespeon** [comment]
That's a fair point indeed. Feel free to open a PR for this change @tjx666 
Otherwise, I will eventually get to it next time I add a refactoring 😉
