### ISSUE TITLE
extension runs out of memory

### ISSUE THREAD

**Issue by capaj** [nicoespeon/abracadabra#78]
## Describe the bug

_A clear and concise description of what the bug is._

## How to reproduce

I was just browsing prettier folder in my `node_modules`

## Expected behavior

does not run out of memory

## Screenshots

![image](https://user-images.githubusercontent.com/1305378/74659321-646b8880-5194-11ea-8b7b-b87ba3510d8d.png)

**Comment by nicoespeon** [comment]
Thanks for reporting. There's certainly a root cause to address here, although it's not trivial.

However, I think we can already address a symptom: Abracadabra shouldn't be triggered while navigating in the `node_modules/` folder. At least not by default. I doubt that you intend to refactor vendor code. Nor built code in general.

What we can easily do is this:
- Don't trigger Abracadabra quick fixes when file is within an ignored folder
- By default, ignore common JS folders like `node_modules`, `dist` and `build`
- Make this configurable

So currently working on it. Almost done. Need to document the usage and ship this 👍
