### ISSUE TITLE
New Refactoring: Implement function

### ISSUE THREAD

**Issue by automatensalat** [nicoespeon/abracadabra#91]
## Is this request related to a problem? Please describe.

My workflow often involves writing the call site of a new function first and then to write the actual function. This means I have to declare the function signature so I usually copy and paste the function name, check the infered types of the parameters and manually add the parameters to the signature. This is a lot of repeated manual work and I'd like some automatic solution for that.

Edit: I understand that technically this isn't a refactoring since it does not involve transforming working code to a different form of working code, but rather broken code to working code. But maybe this would also be in the scope of this extension.

## Describe the solution you'd like

I suggest a new refactoring which implements the declaration of a new function based on its call site. The new function declaration is put in the enclosing scope of the current function.

For example, say I have this code: 
```ts
function doSomething(): number {
  const a = 3;
  const b = 4;
  return sum(a, b);
}
```
The function `sum` is not declared in this scope. I put my cursor on `sum` and invoke the refactoring. The refactoring generates code like this:

```ts
function doSomething(): number {
  const a = 3;
  const b = 4;
  return sum(a, b);
}

function sum(a: number, b: number): number {

}
```
This could also work with async code, i.e. invoking the refactoring on `return await sum(a, b);` would generate `async function sum(...)`. 
Ideally, the refactoring is only offered to the user if the function is not declared yet. 

## Additional context

Here's how Android Studio does it:
![implement-1](https://user-images.githubusercontent.com/26285169/77149094-21514d80-6a91-11ea-901d-462e5185a235.png)
![implement-2](https://user-images.githubusercontent.com/26285169/77149106-27472e80-6a91-11ea-9ca2-6d5983f57a9d.png)

This could also be extended to types, class members, etc.

**Comment by nicoespeon** [comment]
I totally get what you mean because I tend to work the same way 👍 

However, as you said, it's not a refactoring. So I don't really want to include this into Abracadabra directly, or it would be hard to not just include "anything" that I find useful into this extension−and that would be a mess.

…

So I decided to put that behavior into another extension, which is small and not very popular:

https://marketplace.visualstudio.com/items?itemName=nicoespeon.hocus-pocus

I think it does exactly what you want, but it doesn't handle methods for the moment (only variables and regular functions).

The source code is here: https://github.com/nicoespeon/hocus-pocus
